# XLTournaments
# Author: Zithium Studios
# Copyright (c) Lewis D 2021-2022, Zithium Studios 2023. All Rights Reserved.

storage:
  # Valid types are SQLITE or MYSQL.
  # It is not currently possible to automatically migrate from one to another.
  type: SQLITE

  # Only applicable if MYSQL storage type is selected
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: ""
    database: ""
    use_ssl: true

# Customize the discord webhook that is sent when a tournament has ended.
discord_webhook:
  # Should the webhook be enabled or not
  enable: false
  # The URL for the webhook.
  url: ''
  # Link to an avatar to use for the webhook.
  avatar_url: 'https://cdn.discordapp.com/attachments/1028362255785545747/1159605391274037298/XLT_logo.PNG?ex=6531a1ad&is=651f2cad&hm=c0beef7c23632a12fa461c12102e2878c17cb2d19ae46ba90e6d99f4ee7cce40&'
  # This is the message sent when the tournament ends.
  # Placeholders:
  #  {TOURNAMENT} - Returns the name of the tournament.
  #  {1_PLACE} - Returns the name of the first place winner.
  #  {2_PLACE} - Returns the name of the second place winner.
  #  {3_PLACE} - Returns the name of the first place winner.
  #
  #  {1_SCORE} - Returns the score of the first place winner.
  #  {2_SCORE} - Returns the score of the second place winner.
  #  {3_SCORE} - Returns the score of the third place winner.
  content: 'The {TOURNAMENT} has completed here are the winners!\n\n:first_place: 1st Place: {1_PLACE}\n:second_place: 2nd Place: {2_PLACE}\n:third_place: 3rd Place: {3_PLACE}'

# Command aliases to the main /tournament command
# ** You will need to restart your server if you edit this list **
command_aliases:
  - xlt
  - tournaments

# Should we hook into TokenEnchant explosive event for BLOCK_BREAK objective?
tokenenchant_explode_event: false

# Only applicable for PLACEHOLDERAPI objective type
# How many ticks until we fetch new data?
placeholderapi_objective_task_update: 60

# Only applicable for PLAYTIME objective type
# How many ticks until we fetch new playtime data?
playtime_objective_task_update: 200 # 10 seconds

# Should the plugin report stats to https://bstats.org/
# All usage statistics are anonymous and has zero impact on performance.
enable_metrics: true